# Generated by Django 5.0.1 on 2024-02-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderitem_product_alter_review_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
